export { Europe }
class Europe {
    // default color for each country is blue
    russia: string = "blue";
    germany: string = "blue";
    unitedKingdom: string = "blue";
    france: string = "blue";
    italy: string = "blue";
    spain: string = "blue";
    ukraine: string = "blue";
    poland: string = "blue";
    romania: string = "blue";
    netherlands: string = "blue";
    belgium: string = "blue";
    czechia: string = "blue";
    greece: string = "blue";
    portugal: string = "blue";
    sweden: string = "blue";
    hungary: string = "blue";
    belarus: string = "blue";
    austria: string = "blue";
    serbia: string = "blue";
    switzerland: string = "blue";
    bulgaria: string = "blue";
    denmark: string = "blue";
    finland: string = "blue";
    slovakia: string = "blue";
    norway: string = "blue";
    ireland: string = "blue";
    croatia: string = "blue";
    moldova: string = "blue";
    bosniaAndHerzegovina: string = "blue";
    albania: string = "blue";
    lithuania: string = "blue";
    northMacedonia: string = "blue";
    slovenia: string = "blue";
    latvia: string = "blue";
    kosovo: string = "blue";
    estonia: string = "blue";
    montenegro: string = "blue";
    luxembourg: string = "blue";
    malta: string = "blue";
    iceland: string = "blue";
    andorra: string = "blue";
    monaco: string = "blue";
    liechtenstein: string = "blue";
    sanMarino: string = "blue";
    turkey: string = "blue";

}